apiVersion: databases.spotahome.com/v1
kind: RedisFailover
metadata:
  name: vatsim-data-event-processor
spec:
  redis:
    replicas: 1
  sentinel:
    replicas: 1
---
apiVersion: v1
kind: Service
metadata:
  name: vatsim-data-event-processor-redis
  labels:
    app.kubernetes.io/part-of: vatsim-data-event-processor
  annotations:
    tailscale.com/expose: "true"
spec:
  selector:
    app.kubernetes.io/component: redis
    app.kubernetes.io/name: vatsim-data-event-processor
  ports:
    - port: 6379
      targetPort: 6379
