---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: vatsim-data-event-processor-secret
  namespace: development
spec:
  encryptedData:
    RABBIT_URL: AgAnYp6py391eH1UaAWUDqwYddi0ohgbv4xdwUHWFl1MBKRXZUOpVc4RmadXhyr0dZQC3iBP2ZLwc0rQhdC6LO0L78H5HTiYSyvlt8Nz6e/DKJvrMZvtpFST6ODC13XIUt3oeWL9DATUip6EAJ9KgqNXpspyFuNZJVQNkFbrDEu2jHLPDtyEqlxPkIYDKibuZFG8uVspvMLs0rVjBwUn7cdTL5PAab9ELyziZKQan5yyjkarLg1zOt49o5KH86fBhbJIPoeNmEdhVc7KOe/KE6T6UN++SFEgqn1F7qnR3M2dC6Y5XsO5JT04ER77oWZ+cWtxbBRGf6XBDC6EW1Qu5d58k5YPBtsjiY9pvP4Uk/ysH4sI5a5utHqx8woZaDQuDNrHbU4Nl09ZJvXWdWt4YVZKlO7ZrXlapCFu7GNp0hmUZqHyU8eQPCkdUSDKvdjQehRK/kHFJoVZDiYuEPMguk0cHRAPXJOU6GlhrQhnzo2YkdBpQz6VzMTAuHfDwBjEii7KB57Fhv6mm2Y2AfE0wagmOD8A3iUWk7dRTvC04qEwZcbtRidUrPu7ly+LclYRXXtb223R4Ejdc9Cbvj3d83pRyLtQdrUgrO5PyARCACQtjD01cA9uh0z7Ytuk6L+Fgcqn47V6ige2Cpbp0ZvNpycfVTtVug6fUU7L5T1AYfMCFsLi9Yffc9vjiecqRGZeh3UacgBcdooofEs1dbMEcLw7T0XfXk5x6JNZTbyY7nRTshwoxMbb6OH3DvC1v6OHsPMH6g0+bTNLMgwhWEX8qmjMa7f4DgJ3S2JatRK6pnSPCw==
  template:
    metadata:
      creationTimestamp: null
      name: vatsim-data-event-processor-secret
      namespace: development
    type: Opaque
