services:
  db:
    image: postgres
    secrets:
      - postgres-password
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres-password
    networks:
      - internal
    ports:
      - 15432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:

secrets:
  postgres-password:
    external: true

networks:
  internal:
    external: true
