apiVersion: apps/v1
kind: Deployment
metadata:
  name: ict
  namespace: production
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: ict
        env:
          - name: CONNECT_CALLBACK_URL
            value: "https://tools.flyindycenter.com/login/connect/callback"
          - name: CONNECT_BASE_URL
            value: "https://auth.vatsim.net"
          - name: CONNECT_CLIENT_ID
            value: "1546"
        resources:
          requests:
            cpu: 500m       # ~1.5-2x your average usage
            memory: 512Mi  # Slightly above your average memory usage
          limits:
            cpu: 1000m      # Allowing room for CPU spikes; adjust if needed
            memory: 1Gi  # Providing headroom for memory spikes 