apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: production

resources:
  - ../../base
  - sealed-ict-secret.yaml

patches:
  - path: postgres-patch.yaml
    target:
      kind: Cluster
      name: ict-db

  - path: ingress-patch.yaml
    target:
      kind: Ingress
      name: ict

  - path: deployment-patch.yaml
    target:
      kind: Deployment
      name: ict

  - patch: |-
      - op: add
        path: /spec/template/spec/containers/0/imagePullPolicy
        value: IfNotPresent
    target:
      kind: Deployment
      name: ict 