apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: ict-db
spec:
  instances: 2  # High availability for production
  
  backup:
    barmanObjectStore:
      destinationPath: "s3://indy-db-backups-production"  # Different bucket for production
      endpointURL: "https://s3.amazonaws.com"
      s3Credentials:
        accessKeyId:
          name: aws-creds
          key: ACCESS_KEY_ID
        secretAccessKey:
          name: aws-creds
          key: ACCESS_SECRET_KEY
    retentionPolicy: "90d"  # Longer retention for production

  externalClusters:
    - name: ict-db
      barmanObjectStore:
        destinationPath: "s3://indy-db-backups-development"
        endpointURL: "https://s3.amazonaws.com"
        s3Credentials:
          accessKeyId:
            name: aws-creds
            key: ACCESS_KEY_ID
          secretAccessKey:
            name: aws-creds
            key: ACCESS_SECRET_KEY

  # Replace the entire bootstrap configuration
  bootstrap:
    $patch: replace
    recovery:
      source: ict-db 