---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: aws-creds
  namespace: production
spec:
  encryptedData:
    ACCESS_KEY_ID: AgBKW7zbL/iYymSJghAB9yPlLufYcdNkMk6Y/D2dmqigXJarBi/vYHkEXB+V0oUgyrLA17TkRYftPkGA69ltIoR96j1NaZdmAe6dSKTp5p3vSRQWbZtZLD0FlckXV9qMRRtRRk9F8KFhdz86zW1l0IdZFqXHoaBmU+iqRIm5m9wYokhiYbbVPdp+5PKH4KjPgcu+5Pl9sAwMGnjnMj09a4dzq/REt/STd/ljCf0ACnyvwHElbOiwTldOhw8bRt+kP0ngOK9JhRtF2ZIBa+XpoyMrh/v4Ih8eWH8mkHCuXd42i0B/oze4GPIdo5F43ABBmmEZWBjz3LCTWz4JIaXVZuC2oUWkYxFxH2g9iPudgaPEjyjYxg/zZn2259ia8L3t0zGs37A1onsLG6bXlzugyoo9N774uOItA9KDei+EkADCg2yx9bY/8lj0mng2v62Q8UI1ZNzWoycV7UDaVaZGS8WZlRHSDIv2KRWY5b2zpH7HAK5suhuKyMGGDhTjhUhKtGmMBKq0r5DYwUCIjCy7gVWajOw/vk8rsQ6b7bNUoPzB0k7/qvdSXvV+NC/1B7Fs7m2EzJMTLXDbAhOgJL5JNbsG179ZIGf41Pwe/9yTBHKiU720jeImwl2DCEgFsUM85QVtpYPZ7zrUZy92WO94xQkY1QpLlKcDy17Um7nqgIT5IQfCFKKYuI1WPGOgQFt7SrMgI/rAU/i4uh/7Sul0rw0AlN+IRg==
    ACCESS_SECRET_KEY: AgBSIerWiO2BZMx8Ucgg9kn3f/F0JmmAOPf9PjbyHkNMRNxx4GzNyM2QZFQiH+b4BmncNvXdPMD5pFyxvuDMYYIqOK4vZhqEF26phxH7AbZJP8Ww7PMc07AWfI3zcR22Va1y3FdzkA7KTJ/8yeSZ+YmbMn8GMx3HmNH2phyRMVwFCfsOFMSlW+U1HTXJW+9NrZcWHoVDZNzrPu9mW1eJbu7X7qgIjUvPkeNgtwtMQZ9lrJL319FBMmyl0LCTYMOlmBNj6PexMw4mJhPzZek4AzZhi6P0GcAV+pF6iGBIEx4qOO5PxnPY55lrW7cTtSkhaLhZiBYxz1xUajyAfbrlV0IU3rqTICdJ/ZGAihnrmMHTqm4IKsxXZrumQWSA9L8yj1p8CPXAjiqTawgyooop4/kFHIOKke9Np5gwDzlOSwf7V8DUPACQY7Lga1n2zYh8JZzb3c4EGWVkJgk7xx0fAu9kf07mxDWNyoVQ6JkpjzFYIokH2htsSS9mWAaKsG3TVtpR+yCfKT+Wg0d957SoeQK2jCCwl4fRFze9fPC5M5NEQeE6O/dbmtYj+W6P/n66PLHYUmcf8OWrF2XyPOZTrM6HU//kv0DRnrkF+G0hap0S3IO3mgaOG4h0Umzd9sHUbQ0HQFE7UrFvsJTktsevIzrU2tWvooXufMxjSVXPjXhFyj14hD06ErNLyI+vgIIb2XwVAtrrew9q5S6pkUVGeZnh7VANCGLPuhcW+QbzmSZJGNqLPHMub9wF
  template:
    metadata:
      creationTimestamp: null
      name: aws-creds
      namespace: production
    type: Opaque
