---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: aws-creds
  namespace: default
spec:
  encryptedData:
    ACCESS_KEY_ID: AgB/qGteHrvh95MjYn3Uy3v4IachveMDnEun0RqzAcH0aov2ce5BcqGc/TaWDPMevu3nK/BX6fOEw2np9N3PsPpJaXTJqgU0C7103wlk2AMVDZPX/BEdaVR1TcnXspvEci77p+Q1OdMOEVraclgsYrxEEgqzq1aMYIsu5NLLiuUr1QxraFaK2BWntE3tnCLDhfImjWrSPeUO+rubLR4rRtHIMrs31tayK24vRLkMJAl/GNocYh5pfHWhMF8qtOI/p5bAnktBT760zR1PXwrxIxQ8R4tQL9ZxSHUvaBB9R9I8e9tn6pSc5QoaxT3hBbCFv3n0Xt0ajl3aOu9ftBeIX3CSFQUGuu0uP/JOJxstpTpvT8wD20YwOXY2hli2hHyPdVV0t18GgElIDRZHOaVT7SqZP6hIfgrh9X85b+0YRS+aXwRCGSLja9S24pjk8jyadcqcTYkmM4mirRpl41glkYqrXxXP8Qrx276UJac97cC7TIvEWtPBp+V09PtSSULAlvcdhNQMZUVfPAwkoHeOMf+UMv/8PyYoLt5KOjCGB6AmGsX5sssoJWQdU/pAolsl/FEv5X+Z/NSLeWNpoKQWoEAaj3bM3k3kMuHrWx+wTHsPN+MyTCbJUf56NC03yFslAxRKWQR0hIR85BnUAVEfl2gIu6hfVtRUECrpXQ9IT9BWiU5RRiAQXdVpoq0nlRt4lx3ee1/gJIzJ
    ACCESS_SECRET_KEY: AgDIJup9VsFZNrFPVTIKqSnMuLwCauqZcZKDslZbosWiIDY8yQaSGzKL/oS03E8dHg7arwaxpMAQPbAbzYG/wbaoaCRu2rnVKk78D+16+dtTMDpyKD0vjo4Fv8kWxZYfI8h3POxS9wDsprtyRVvOOLHriCUJPHT4avmcZ2FrEg69xbyzjrO36WbPjR/tgQu5yUKH+3x504bnqv8OIfcEABJd/enAZwNl3EabDN7SKWo8uUyw3LEewdxZkggk7GUAeH6zivrtljE+G9cnLE6iP/uOwPWYptebaC3X1v8qjOBPtMAXzw9FMHAOX3HEMKDLKyODN9yWSqHmv4nSBoSmbtV6tchk2EPWxBBvHYwQtw/tCgHK0MGghyMKUNvnsz6gS0qQ3f4PEzutbVfdajpFDKZbsaLKMJ8pbghSnE6LO9jIPipbZquvPZDfyjwurfRexk2eFB3Q/24cxTkVOeGQV1EJzobMqoVHV27rANWxkz2WH2Iz+S/0gA09C0hTxOBJzPVVNSUanI/JANDZQ3TCWhmcZd2zjqZMB1cbQ8XBJZWx2+S+s8TtEp25/lVFgBlz9eR4ExN49IaDaib3+0lh8AftzxNJysVHcjuVRCOYi6iVIj1nDJKRe5z0oBCI37DVEfv8xJFdNjwn7uZo7k9JKJ2shgR8qVxCQERrmu3OMOV4nasxLWbMsucQToa54N10NmQjFWo=
  template:
    metadata:
      creationTimestamp: null
      name: aws-creds
      namespace: default
