---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ghcr-secret
  namespace: argocd
spec:
  encryptedData:
    .dockerconfigjson: AgAWXYIyOKNlz5+oiNMNzVIoj+4wtIL5wuzkJ4+Jt2YY2EEEQdWh8rggln/dgW+61RTGKUvNqBDinegxhJ7RQPjGiFmFnEvuxGpWxzA6M5KuAITqUCD9kkrEMDcYpsNkEXR/52jdrEBJpPnW/jgjwqYTxFG4PXCfZDt29jvSlr5yGog8PKJynpcL+g5mM2qPXlzPeV4WP+Y5ZVEaPXOX2uHV9r3arOlOdoVi0iXIvzR+7PqaFN1YWiw83WHlgP3DQBNYIrNcD4ceeiw+YIN8QxtjO6BJ6we6DKj/BgWx/YRqI37740YuYRlE6NPfj9u/HVIAHLByl10HlrS6ydyqgB4RKYZTPlXsrDqEqycOkSBclcNT6TFsj4zQ6Ge8UE3qv+Bj/Nzjd5qBf5cVIjrzPl+2YK27wWHu5gt1AWimF3YTQihjD/o1rKnOqPnC86WxDhIEqymAG7oe1HtuwK7lETCDf2OfHews3dBpdUKq8hxwOPM8ZJqiDNnovKW6UbF48LMsCubJvGdo6NXI1E+qJnyTlJU4xW7mGUzxR0dhHIjJh6Hq1KEI3QDJQRn6Yb/lV2mHVboDeQQjfu69PV7Bit+9Y2/JRfEi/1lVw1ZGePeqqPq5kNpk3vzH3K9YYdQD5bXq2om6LFdwaQ9abQyzATDeLwlLioJkgcuhalmgm4He8/EA0nWRI9wkRPGYppl8pOzCbn39eGw2lgio7hCAvEAuHGzVM6tpRrOwu/BOpBkjE/+u+4rFhqDQcBaDiXkYrIhQIBoGVU7XnqISJ5BRn2DyXJOxZ6/aQZlbByWP+wXShO/PeTWNLlaLjqcJM9pBIZ5DcAu23OEbQ6yL2feXVYc9RpJweg4Ys2Q0OU/G9Omkn78ugafvL+M7s+kKNwo+FEfszaO4ri7uQzX7TGRZmOizLYzAfO7zilIYUOI=
  template:
    metadata:
      creationTimestamp: null
      name: ghcr-secret
      namespace: argocd
    type: kubernetes.io/dockerconfigjson
