---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ghcr-secret
  namespace: development
spec:
  encryptedData:
    .dockerconfigjson: AgBzwE3ko0DYBzDvaabVHkBGErJCKVmn2FLxstKjfosTTsiFxXW3gvdmKS7wC3x4iQsjo1IqMeI70CR+JFqj5LZE9UA3CzcsZ/xLrX/G6u/vWb2HmnVy0PopYlha7Z9s4oO5B/n5VcXmdUlSWhlUfiByfQJL7um419ivBXjviKlvgoO7jb/mJENVjePWlDyqvmnTtydrU1hzr6StWDPtNfUdPy7IVNgs4rKxtk/njODrb/boS9cNiqmxsZxYiN+MH4m3afgQlDxRrMurqP7o+nZzzM+xWtlNn9yrB3qiwoVPSbpDxc1yxJruM22i1gCMOtMVdgASmFBQ4fmwdcW/GUHt/qUcDJ0qmsKM3CrU5UXoOmVzqNpMM91i2Mh2wJ12BPdRL1Mx8bsIv4BS40LyoyjB/mVaouK+3fPl5CHM9YwdwnjfeqJQkfOnB8Prw+QJUeMghKt5QR6nQiMiRfqmdpPFsSgBAg3nj6sbnad2LWq86kERX7mfyf+mY69xd9Az/Iig8vpS3bYKyZtNtIrtlf8PnsmY5xhc+bjyhUG5QWasi9P1GpItb4yq7V+vWLzGgnY7X/zIlsop3ltlUqWMyXmU++VtvAZsGIot45jC8MXNhwWcPjQEdo1yOLc4WfdLFoNAJrl3F6urEWaWdiTQb0H2/OZ2paca0B+tcUaY+dhvc6lwziIfaO2FFA28yqxo8B8cNrnOV6Xc01NBRdxxg3/fzY9U0v1t8hSr6rB43e5Pu1j83HV/rw1YE9ITMwqPofcDKbRAxb/iR6VDuKqqwud5fnWWyvlYW005bEeNgk5ItCyGWIXAx6Q6zUhvSkE0o7ReG2ZapmwfQWdXDIuQA9Tuq2271y6PhL4YvsBbDST2SRvAjJ1rGJ9uoo7uWosL1/dWuvEIElARhwBodwjR/TiSR0guCmmwPQOjdok=
  template:
    metadata:
      creationTimestamp: null
      name: ghcr-secret
      namespace: development
    type: kubernetes.io/dockerconfigjson
