---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ghcr-secret
  namespace: production
spec:
  encryptedData:
    .dockerconfigjson: AgAuLe7V0/SBv7h1AyTIQELSRUaENpKAckCKcAh3C8bZKzpauTzmovyTPFEUDuA4HBYVOy4xZ0mKHUCfmlKK4mmACsFcVwl0WutTmrvjH9e0IIhqmPQMevVVVeGmiHqhiHlpxb/VpcqESyUEo0BwdWVeb4zs3Tow4saQKLhaEMuW0H0PY2kPSLz0fcJ/rx31T8c1pQQ8fBkOe/VHDUAcxDRLoQcDfoUvlabgCskaLRqcKzDdP5/pEJvT8AkekhXtxBy3/GdxxhYBYsRjZvrsJpRl1pVmld8lojCdLOkTBYpnlgglEpw+STn7kjZA0Ye8Zj/eYjf6wgyjnImmxrWnSgsE8p2QIa+hnx4FRHUMHhgK+iYd4oXh36jpD2li+Cf6wait+mu5ianCzwfqMyXrjjYhLo3s3WTvDqpXWyi32SiJT0Py4YPH+C9hfKyeNubQG+Xsl1CF12Kn874MWvEoLeIO8s7oKqYLvQCJtCQn1sn/Xrs+5uIb0H0hdjHkUL2voUKwP5tj5SGm2DpBuDtNRrrAy6yWAgWSfE+Z6SnZUXIDbWVfmZmF5FMmwD6c8ttRVjkgozBXYI6zFhCrNDMuYDjutSTxBFOdHHABk/PmJQQeq+G/mtaLt3J7Ihyn0eQ/SFIZr9Zvy+b13XWkeJLA0uM1r1Nvs74R0mxGi9p/gpMYq60c+edH5uvGl9II4wSaaLw1tkxlDJXBRdUc3urMfoNUclxQ1lLNMEu20ofjfOgciiRORMX4ceLxmJId8Sgp+nDPmb1rFveEvKI47CbpOqtBFTTVvJniWtdzMf+R3qwEKwjEmMJxPTrKO9k7MuV894XgbNdmm8vVSQy57ZY7JanUW9BIWnUtQnjK5wttoOzju6FlRNnJkAkwC1crwKEFXvBvAtNS2AgCh+HP++YyhGQ5bjsaN7AT03ANSlI=
  template:
    metadata:
      creationTimestamp: null
      name: ghcr-secret
      namespace: production
    type: kubernetes.io/dockerconfigjson
