---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ghcr-secret
  namespace: default
spec:
  encryptedData:
    .dockerconfigjson: AgBRsJY+0F0eV3p35ndI4UQbVRGI1zpC5H0XSYH/MB4WW0ZlOBkvGOlbMgB31do5pWLu8ge3urXNkPoM61r1cfR5nHHXSzipk39vZuLY6mmccWlLmN3kqZ92z6mTqB5LhKHlxA2yvTmGsNU2wpaTOwmleZecrx9CR9X6I8TTVAQNvc/mkDcbRIIrs5geR4b2r7zGMANDCYTjb5nIlTyruPdmVmk3BZRQTmdgoMMuGpVHZ37No8YWtoBgRVLR65ohGeDP9bKZ0q9BKLctrUwWNC+sGYYcB3ulPw8PvnySVkyLyTiPVxFSOUMWTM24xZrkP8o7jgGHXIE0SC4E+1FOVLUEPnvspAUslgUObMpOpNuvOJtSLVpjvMbLi3vScA4DsS+MmGSRlogdKhMX8CPi1fI+W+PC690LOuw9NavIWOUyUQHuXVr6SO3tgJF/jrsDo/zPA/lhja48qVAqoZbS2+XB5j6I6j8Fqx0wSCt/TF6Chd8PiWn+Vfp63PUvTxco009PqOHnZjIl53cRM+mQndmtmtvxOqeQbmoRHimY6344HWUW/PT2Mm5NcBhwNyYxeWt/IK9S+K0xvt8qVnVE4gxQOoanozfRoqJEVc52kUeVz2Wjh+z9jc9/5zDlB5wwbwb4aZwbqImx3HBSiHvHbYeeKrd3l8qPgt5cu9tO57McZaqLZqvr++JPqvCOJS8w4p0fYGRRAzecfFFKttrhxoFrV5LYleF18keaukZ/T/O4LSsnMZZE9G9E/yQ9LHKKpuqn8Yj10d6jJ+5dlcq02wg0Frx3NKJ+h8WD1fgzR6fRIWEvfnD0RSiaY00fMJqwqQ4iJ3jlUW7ot/IKaqc9eTUpGuSpl2aGsb1h0rNQOWoOgM6Da1dr+9FJyb51ec3HCw/8Wijdp5NlqCU0OvNU05XC7i3eAnXtz+JpBiY=
  template:
    metadata:
      creationTimestamp: null
      name: ghcr-secret
      namespace: default
    type: kubernetes.io/dockerconfigjson
