apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: vatsim-data-db
  annotations:
    cnpg.io/skipEmptyWalArchiveCheck: "enabled"
spec:
  instances: 1
  logLevel: debug
  postgresql:
    parameters:
      max_connections: "100"
      shared_buffers: "128MB"
  
  resources:
    requests:
      memory: "512Mi"
      cpu: "100m"
    limits:
      memory: "1Gi"
      cpu: "500m"
  
  storage:
    size: 1Gi
    storageClass: local-path

  bootstrap:
    initdb:
      database: vatsim-data
      owner: vatsim-data

  externalClusters:
    - name: backup-source
      barmanObjectStore:
        destinationPath: "s3://indy-db-backups-development"
        endpointURL: "https://s3.amazonaws.com"
        s3Credentials:
          accessKeyId:
            name: aws-creds
            key: ACCESS_KEY_ID
          secretAccessKey:
            name: aws-creds
            key: ACCESS_SECRET_KEY

  backup:
    barmanObjectStore:
      destinationPath: "s3://indy-db-backups-development"
      endpointURL: "https://s3.amazonaws.com"
      s3Credentials:
        accessKeyId:
          name: aws-creds
          key: ACCESS_KEY_ID
        secretAccessKey:
          name: aws-creds
          key: ACCESS_SECRET_KEY
    retentionPolicy: "30d"