apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - https://github.com/bitnami-labs/sealed-secrets/releases/download/v0.28.0/controller.yaml

namespace: kube-system

# Optional: Add common labels
commonLabels:
  app.kubernetes.io/part-of: sealed-secrets
  app.kubernetes.io/managed-by: argocd 