apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: tailscale

resources:
  - https://raw.githubusercontent.com/tailscale/tailscale/refs/heads/main/cmd/k8s-operator/deploy/manifests/operator.yaml
  - tailscale-auth-sealed.yaml

patches:
  - patch: |
      $patch: delete
      apiVersion: v1
      kind: Secret
      metadata:
        name: operator-oauth
    target:
      kind: Secret
      name: operator-oauth 