---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: operator-oauth
  namespace: tailscale
spec:
  encryptedData:
    client_id: AgBGyon8HPJG/Yqw0o3W7LOf9hG64wAjeHAK/MqLe7Xg2phBGCkUzM/3vbdg3Vb5NTCoLav37gV5xxTf5+AYTFP2dEehAB9oAf8+rQ+F9QN6AlJmHsfpy1TCp6sTMan+EHTacIPm4JQcfg0ym6Wb2s4gGSXbpNzEVOZJWOMRrvLfAiX31uoT0jyKsWupcfICuxTyx6fpMgbtdFusv5RTnUkfcT4xaOQ5HGoSV0Kw/V0epMh2e16Q4UJZikYqOpniO/ZbovSbMp20Jnm0NbV1uZvG+xawOqJ5/ECFxUKt0cRsrOxi8eSe/ZH5xN1NcwaLzmfpI5HNJ3fUUi6V0uA8pNtL1GDvWsqEMqancuh7BqWCZumkBg4wuZJrIbyc+r7Va212kfPirLiU3kdkKFTQvGGEcivOucK79G1Q5LBVR88NX8wkWhpiLpcUkAynZe71ZRhHHIFohW4xbMONpAhdgNfgmPbk9mVJ1emEQ8P3hKWXS+SvWEBDrSqjkDBO0H6MkQImlIH2FsjBjxrnQXionjuB3RzPbFQPuYG2kAs1Uc1GQkPdFcT5H4HNQdgJepsl/+6BSzSi4Brt8hQQLplOys3bado0GDQgCrL/AdDAh3yOPU5j8ps9oqivSGEZMy0wKpnQ5XYEE9ylVu4ChVfXB908X8O55goSD9MWw977jSxNL4Od1pgR+yyvTtSBtV2sqbNWeUjBBJpiRjOX3JrE7SC3uA==
    client_secret: AgAf8GK0wiFywoMOHloTvBg1EZtDt2/UpEd+7x++BtjkjgBYRWgI/KxnKeaoXmjTWoQBeOO1VtRgvjIkqGVlbsLuy18dOyRX/2/3L+lguznmr73mQKQVfbabaSFiJ21MteRHQr/RtwQ1ri5E3v1927WPi9biqSsAz8jy1i4IhJB84V0B5aO5oqxyAFwEXk3X0B6Jf7/GsIv+WFzuDyFiVluT7XPTuKtEQ1ev2coo3YtzwdiP2YyxVvzKeaFtuIyimfFRKU4ctqj2hB7hrb0IzESG19iCWNjp7efzsc9hsgUxJCpFDX0VhgmZIQJdg6inK/x7bV69k3T4vwqx+w41+VzPT4okAlknQVwH+m3kXnahyR/Q51z45p7vgk45qp0uWwISoE9uugEEfFE2WVewp33bRpBoH/hPohAh/dLlTO9x+ZBZsxOD2PhCSR72xtb7/l/s+Wb9sMsx/0wWaQhaGHQuqSBK/K9toMo48fjSwXwHyRwjv4yjPizp7IKSz5q+16JDiRbskoMkL24O2A5ceWoezeC7D6VaDkRPs7G5dYvWIyQOr3o91Joo5W+kaWDTaHpFLjmku84CIlVrIQ249oYFw8m/ycKDyEvbCthyimTX9dHIawHAvdNq79XTWtgpOgpaCZMgwPz2NIUS+dO6DGfZYkp6F0Ib/9KFG8aMBRHUYfr4K12c4csXDDCb3OHnsM828cSIDLsyBMjdEHtEcLih7RU/ZvHnPFa2A4xbO4FCelZ9Do0llnboxRkpg7KvV7eW7l0BIQatwM9tA+zrHidj
  template:
    metadata:
      creationTimestamp: null
      name: operator-oauth
      namespace: tailscale
