apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
  labels:
    argocd.argoproj.io/instance: traefik
spec:
  valuesContent: |-
    additionalArguments:
      - "--metrics.prometheus=true"
      - "--metrics.prometheus.addEntryPointsLabels=true"
      - "--metrics.prometheus.addServicesLabels=true"
      - "--entryPoints.metrics.address=:9100"
      - "--metrics.prometheus.entryPoint=metrics" 