apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - https://github.com/rabbitmq/cluster-operator/releases/latest/download/cluster-operator.yml

namespace: kube-system

# Optional: Add common labels
commonLabels:
  app.kubernetes.io/part-of: rabbitmq
  app.kubernetes.io/managed-by: argocd 