apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: redisfailovers.databases.spotahome.com
spec:
  group: databases.spotahome.com
  names:
    kind: RedisFailover
    listKind: RedisFailoverList
    plural: redisfailovers
    singular: redisfailover
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              required: ["sentinel", "redis"]
              properties:
                auth:
                  type: object
                  properties:
                    secretPath:
                      type: string
                sentinel:
                  type: object
                  required: ["replicas"]
                  properties:
                    replicas:
                      type: integer
                      minimum: 1
                    resources:
                      type: object
                      properties:
                        limits:
                          type: object
                          x-kubernetes-preserve-unknown-fields: true
                        requests:
                          type: object
                          x-kubernetes-preserve-unknown-fields: true
                redis:
                  type: object
                  required: ["replicas"]
                  properties:
                    replicas:
                      type: integer
                      minimum: 1
                    expose:
                      type: boolean
                    resources:
                      type: object
                      properties:
                        limits:
                          type: object
                          x-kubernetes-preserve-unknown-fields: true
                        requests:
                          type: object
                          x-kubernetes-preserve-unknown-fields: true
                    storage:
                      type: object
                      properties:
                        persistentVolumeClaim:
                          type: object
                          x-kubernetes-preserve-unknown-fields: true 