apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - sealed-ict-secret.yaml

namespace: development

patches:
  # Set replicas to 2
  - patch: |-
      - op: add
        path: /spec/replicas
        value: 1
    target:
      kind: Deployment
      name: ict

  # Database secret patches
  - patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/env/0/valueFrom/secretKeyRef/name
        value: ict-db-app-prod
    target:
      kind: Deployment
      name: ict

  - patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/envFrom/1/secretRef/name
        value: ict-db-app-prod
    target:
      kind: Deployment
      name: ict

  # Environment variables from deployment patch
  - patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/env/1/value
        value: "https://tools.next.flyindycenter.com/login/connect/callback"
      - op: replace
        path: /spec/template/spec/containers/0/env/2/value
        value: "https://auth.vatsim.net"
      - op: replace
        path: /spec/template/spec/containers/0/env/3/value
        value: "1566"
    target:
      kind: Deployment
      name: ict

  # Resource configuration from deployment patch
  - patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/resources
        value:
          requests:
            cpu: 500m
            memory: 512Mi
          limits:
            cpu: 750m
            memory: 1Gi
    target:
      kind: Deployment
      name: ict

  # Image pull policy
  - patch: |-
      - op: add
        path: /spec/template/spec/containers/0/imagePullPolicy
        value: Always
    target:
      kind: Deployment
      name: ict