---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ict-secrets
  namespace: development
spec:
  encryptedData:
    CONNECT_CLIENT_SECRET: AgBV7tKf0UKvVdPtMS0NrYkyzxQmWUJVFqfMDL+9oWgum65TkzVfntskTdpQ3ALkP2T/uR+8CDsmKg0jQhQLs5+08Zp56J9N4zT9OFYAXeNuFWKDdBGCMON6y1Bfu/RST4AdWdDPPOGsbLZ8J/JgYp729ah5sJvbdabD9anP2uoW7oTKZFJeBcsZ2Y9J8IkfbaZ5BqyNQbwiWosjMYt8/6lScbFwHA2291XmXA0O9N/BBGmVtodo/HFzef5qUPT4cyxmQoZqmbuV+zMvpnWM9wB3IFoARljaE3+mm3UWq0wrG+oxhPTJWH3JoQNn8CGeYCcy4n31xI5Ul+L7YVDiPx0PrnAgwAvXiB5CIg/oXk4G/k4803IxZnbM7IT0iqov3F1BQg9DxjBZbfcgQ6G4wofhVk+SyjmNnDGmtVM/SaHSl8RcULwoKv06kIJ8ktO3kLYN2KIM/sHjDRKH5w5ON2lGIRejSsvyfiBRHnEkOZcUTC0N3YuYN8dWLfPbAa3zwMtJsFCpjm4vwbhsEuh2VBHP07fIlecnfCVPM7rkeaR1Nv94wc1ZkimvvEDz+D/yAouW68RN2Nh7gdsYfUY9/EZHCGfXb+C1dIQRbVM0R5zMmFM/sJP4gkvtIoQdgGNnIfY4rs57oQBfy0qVJXDgZoo1r3k01YQaqk/L3Vx6RoiaV46ILBkeVEZXaFygNEZjRrU4qkKmA9QEnb92f7G214GLtenDas/iUuYOUSV0fTng8LPeje9c9nWm
  template:
    metadata:
      creationTimestamp: null
      name: ict-secrets
      namespace: development
