apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
data:
  url: https://argocd.dev.zid-internal.com
  server.insecure: "true"
  admin.enabled: "true"
  application.instanceLabelKey: argocd.argoproj.io/instance