apiVersion: argoproj.io/v1alpha1
kind: ArgoCD
metadata:
  name: argocd
spec:
  dex:
    openShiftOAuth: false
    config: |
      connectors:
        - type: github
          id: github
          name: GitHub
          config:
            clientID: $dex.github.clientId
            clientSecret: $dex.github.clientSecret
            orgs:
              - name: Indy-Center
                teams:
                  - devops-team
  rbac:
    defaultPolicy: 'role:readonly'
    policy: |
      g, github:*, role:admin
  server:
    insecure: false
    env:
      - name: GITHUB_CLIENT_ID
        valueFrom:
          secretKeyRef:
            name: argocd-secret
            key: dex.github.clientId
      - name: GITHUB_CLIENT_SECRET
        valueFrom:
          secretKeyRef:
            name: argocd-secret
            key: dex.github.clientSecret