apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - https://raw.githubusercontent.com/argoproj/argo-cd/v2.13.3/manifests/install.yaml
  - https://raw.githubusercontent.com/argoproj-labs/argocd-image-updater/v0.12.2/manifests/install.yaml
  - ingress-route.yaml
  - certificate.yaml
  - argocd-secret-sealed.yaml
  - notifications-secret-sealed.yaml

patches:
  - path: cmd-params-cm-patch.yaml
    target:
      kind: ConfigMap
      name: argocd-cmd-params-cm
  - path: cm-patch.yaml
    target:
      kind: ConfigMap
      name: argocd-cm
  - path: dex-config-patch.yaml
    target:
      kind: ConfigMap
      name: argocd-cm
  - path: rbac-cm-patch.yaml
    target:
      kind: ConfigMap
      name: argocd-rbac-cm
  - path: image-updater-cm-patch.yaml
    target:
      kind: ConfigMap
      name: argocd-image-updater-config
  - path: image-updater-deployment-patch.yaml
    target:
      kind: Deployment
      name: argocd-image-updater
  - path: notifications-cm-patch.yaml
    target:
      kind: ConfigMap
      name: argocd-notifications-cm
  # Remove the default notifications secret
  - patch: |-
      $patch: delete
      apiVersion: v1
      kind: Secret
      metadata:
        name: argocd-notifications-secret
    target:
      kind: Secret
      name: argocd-notifications-secret
  # Add node affinity for ArgoCD components
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: all
      spec:
        template:
          spec:
            affinity:
              nodeAffinity:
                requiredDuringSchedulingIgnoredDuringExecution:
                  nodeSelectorTerms:
                    - matchExpressions:
                        - key: node.kubernetes.io/role
                          operator: In
                          values:
                            - ops
            tolerations:
              - key: "node.kubernetes.io/role"
                operator: "Equal"
                value: "ops"
                effect: "NoSchedule"
    target:
      kind: Deployment
      labelSelector: "app.kubernetes.io/part-of=argocd"