---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: argocd-notifications-secret
  namespace: argocd
  labels:
    app.kubernetes.io/instance: argocd
    app.kubernetes.io/name: argocd-notifications-secret
    app.kubernetes.io/part-of: argocd
spec:
  encryptedData:
    discord-webhook-token: AgC+G8aAW1BeX3QF7GXZNk3pIksrk4D/PJcn2UPX+hOQ15enhotij1n5RcvphyABqIwLHNrgtG4qy0x1J/cYAa+jEHGiEfgEYVHGURS7229WIMQX8Dyq+yRj0JR+EYNXGukolr+9eBevCqr6T4nTV0Gi9qFoxHkHKJzgEosYepP/Wb4CC+sooJMjmd8Gs6JYNfzPmWP03GsCKUVEgRJ7ktUctrG7RP22OCFxQeFm8KdevofbOif5q5CVctgb2Hjur7tUt3ELfyyO5Q8/PMAPEmL1yxeIeY3xZ3t5FWBfXZdrz4piXdoAbGaVhzRl7MLAbXZ9R0tOpRAM+QiaSkpfaEEeJ/YiC5PIFc655Zk/iHU9pAGtWuaI1/VVuffzIsXxMXFQd042W1S25GYOE2bMQTVQe+XgyuNEXMc5Mu9ALUg4VVhhjWILib0kVPgT6GFdthMDie16J1ZoKFXeNcWA/6joOq98DsprYHLW3Szr3kxGbVD3fHrmZMlFGIhwpZTFgGvwg4Agf05T7nL1N7xEYlhNM4LSH8XCQPuzHLIoMaRZzdVqNnErjszH1o59+XsXt1NoORADk9WVWGAQkZI+qosnpxQQygoUe7yjRHs7XF1sFPK86Q1D44wLPjcNfExhHuWme7jAEXXoEA2VxZr53IRLikteE4uxtCkydcNMXECPHKcGMqQhZ8pvoLAiqbtKgLrfG08QHE1oQV9VOh8BPSamL8ega10MdC5PRCsMOFJ+GSV+Zy1tYhBGX7VOMdkX2HRkDRoPyvrazZyZT5g+nJEznDz1GQXfresNf/EtSDB9tgfp5tcVAiY9IXde3riOnvUia4iKU2lMqlQOiuTwsrl4unArQRqWGmDO
  template:
    metadata:
      creationTimestamp: null
      name: argocd-notifications-secret
      namespace: argocd
      labels:
        app.kubernetes.io/instance: argocd
        app.kubernetes.io/name: argocd-notifications-secret
        app.kubernetes.io/part-of: argocd
        app.kubernetes.io/component: notifications-controller
    type: Opaque
