apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-notifications-cm
  namespace: argocd
data:
  # Service configuration
  service.webhook.discord: |
    url: $discord-webhook-token
    headers:
    - name: Content-Type
      value: application/json
  
  # Trigger definitions
  trigger.on-deployed: |
    - when: app.status.operationState.phase in ['Succeeded'] and app.status.health.status == 'Healthy'
      send: [app-deployed]
  trigger.on-sync-succeeded: |
    - when: app.status.operationState.phase in ['Succeeded']
      send: [app-sync-succeeded]
  trigger.on-sync-failed: |
    - when: app.status.operationState.phase in ['Error', 'Failed']
      send: [app-sync-failed]
  trigger.on-health-degraded: |
    - when: app.status.health.status == 'Degraded'
      send: [app-health-degraded]
  trigger.on-sync-running: |
    - when: app.status.operationState.phase in ['Running']
      send: [app-sync-running]
      
  # Template definitions
  template.app-deployed: |
    webhook:
      discord:
        method: POST
        body: |
          {"content":"","embeds":[{"title":"✅ Application Deployed","description":"Application **{{.app.metadata.name}}** has been deployed successfully.","color":3066993,"fields":[{"name":"Revision","value":"{{.app.status.sync.revision}}","inline":true},{"name":"Namespace","value":"{{.app.spec.destination.namespace}}","inline":true}],"footer":{"text":"ArgoCD Deployment"},"timestamp":"{{.app.status.operationState.finishedAt}}"}]}
  template.app-sync-succeeded: |
    webhook:
      discord:
        method: POST
        body: |
          {"content":"","embeds":[{"title":"✅ Sync Successful","description":"Application **{{.app.metadata.name}}** has been synced successfully.","color":3066993,"fields":[{"name":"Revision","value":"{{.app.status.sync.revision}}","inline":true},{"name":"Namespace","value":"{{.app.spec.destination.namespace}}","inline":true},{"name":"Operation","value":"{{if .app.status.operationState.operation.sync.prune}}Sync with pruning{{else}}Sync{{end}}","inline":true}],"footer":{"text":"ArgoCD Sync"},"timestamp":"{{.app.status.operationState.finishedAt}}"}]}
  template.app-sync-failed: |
    webhook:
      discord:
        method: POST
        body: |
          {"content":"","embeds":[{"title":"❌ Sync Failed","description":"Application **{{.app.metadata.name}}** sync operation has failed.","color":15158332,"fields":[{"name":"Error Message","value":"{{.app.status.operationState.message}}","inline":false},{"name":"Namespace","value":"{{.app.spec.destination.namespace}}","inline":true},{"name":"Phase","value":"{{.app.status.operationState.phase}}","inline":true}],"footer":{"text":"ArgoCD Sync Error"},"timestamp":"{{.app.status.operationState.finishedAt}}"}]}
  template.app-sync-running: |
    webhook:
      discord:
        method: POST
        body: |
          {"content":"","embeds":[{"title":"🔄 Sync In Progress","description":"Application **{{.app.metadata.name}}** sync is in progress...","color":4037805,"fields":[{"name":"Namespace","value":"{{.app.spec.destination.namespace}}","inline":true},{"name":"Operation","value":"{{if .app.status.operationState.operation.sync.prune}}Sync with pruning{{else}}Sync{{end}}","inline":true}],"footer":{"text":"ArgoCD Sync"},"timestamp":"{{.app.status.operationState.startedAt}}"}]}
  template.app-sync-status-unknown: |
    webhook:
      discord:
        method: POST
        body: |
          {"content":"","embeds":[{"title":"❓ Sync Status Unknown","description":"Application **{{.app.metadata.name}}** sync status is unknown.","color":16098851,"fields":[{"name":"Namespace","value":"{{.app.spec.destination.namespace}}","inline":true},{"name":"Current Status","value":"{{.app.status.sync.status}}","inline":true}],"footer":{"text":"ArgoCD Status Warning"},"timestamp":"{{.app.status.operationState.finishedAt}}"}]}
  template.app-health-degraded: |
    webhook:
      discord:
        method: POST
        body: |
          {"content":"","embeds":[{"title":"⚠️ Health Degraded","description":"Application **{{.app.metadata.name}}** health status is degraded.","color":15105570,"fields":[{"name":"Health Status","value":"{{.app.status.health.status}}","inline":true},{"name":"Namespace","value":"{{.app.spec.destination.namespace}}","inline":true},{"name":"Message","value":"{{.app.status.health.message}}","inline":false}],"footer":{"text":"ArgoCD Health Alert"},"timestamp":"{{.app.status.operationState.finishedAt}}"}]} 