apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-rbac-cm
  namespace: argocd
data:
  policy.default: role:readonly
  policy.csv: |
    g, Indy-Center:devops-team, role:admin
    p, role:developer, applications, get, apps/*, allow
    p, role:developer, applications, sync, apps/*, allow
    p, role:developer, projects, get, apps, allow
    g, Indy-Center:developers, role:developer 