global:
  resolve_timeout: 5m

route:
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 3h
  receiver: 'discord'

receivers:
- name: 'discord'
  discord_configs:
  - webhook_url_file: '/etc/alertmanager/discord/webhook-url'
    send_resolved: true
    title: '{{ .CommonAnnotations.title }}'
    message: |
      {{ range .Alerts }}
      **Alert:** {{ .Labels.alertname }}
      **Severity:** {{ .Labels.severity }}
      **Description:** {{ .Annotations.description }}
      {{ if .Annotations.runbook }}**Runbook:** {{ .Annotations.runbook }}{{ end }}
      {{ end }}

inhibit_rules:
  - source_matchers:
      - severity = "critical"
    target_matchers:
      - severity =~ "warning|info"
    equal: ['alertname', 'namespace']
  - source_matchers:
      - severity = "warning"
    target_matchers:
      - severity = "info"
    equal: ['alertname', 'namespace'] 