apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: cnpg-monitor
  namespace: monitoring
spec:
  selector:
    matchLabels:
      cnpg.io/podRole: instance
  podMetricsEndpoints:
    - targetPort: 9187
      interval: 30s
      relabelings:
        - sourceLabels: ["__meta_kubernetes_pod_label_cnpg_io_cluster"]
          targetLabel: cluster
          action: replace
  namespaceSelector:
    matchNames:
      - development
      - production 