apiVersion: 1
datasources:
  - name: Prometheus
    type: prometheus
    url: http://kube-prometheus-stack-prometheus:9090
    access: proxy
    isDefault: true
    jsonData:
      timeInterval: "30s"
  - name: Loki
    type: loki
    url: http://loki:3100
    access: proxy
    isDefault: false
    jsonData:
      maxLines: 1000
      timeout: 60
      liveEnabled: true
      derivedFields: []
      manageAlerts: false
      search:
        hide: false
      nodeGraph:
        enabled: true
      health:
        logQuery: '{container="loki"}'
      alertmanager:
        implementation: "cortex"
    basicAuth: false
    withCredentials: false
    version: 1
    editable: true 