---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-oauth
  namespace: monitoring
spec:
  encryptedData:
    GF_AUTH_GITHUB_CLIENT_ID: AgAxX+D2johJvirwJU6ygOLCqqaIMJw4HES8r+fhejl/LeMVLxWTZSnvNnWSl4l7Sswz04cwnbuCWrw+mMDVTdDD36bSBZSMl8+fsCWPsE2vLHjM4K0esERsBLwpVTEJg1pIN9I5etszc0QW1oCDNPs3mFsT+YAWMHJL4CzMzjNBt3Oycu3d3j4pzq2Fgyz/TFQQ0KUcsZ2w5DLglGxNjZgqk1tdqJ+47++hO7MY9e2F/Ob1pfF7wMVXV5Ymt1nxcTDXv3HstUFhz6zKYI1Ez6as2+I0O6KBVcEgq9YomKvVCOo6hNsTbv4Ms8GbP4f81t1i6wS7uh96ID5Hh9BFwtXE68sAGkRaFLeb2TOcFc8IzzizxiyTuKhE9f0c3eksrVKIsIAygKdJZVhLhj2RQ9j6nzoXyr9v2qoLcGlbi9HNMozuWBRaZ6RVtC1mOZSX86HvThwo7fD29DxXFFCp+lY+Fhv0pDVOmn7uT++0VjfMu/hqrzGm8ha0HJ44l1RkttTn+jo4vP3Rts+Zr29sr3RJZbOIi1WfGr0mmM3aggbOlSyVOL1+0ftg5twTGlVGgGkIh0oC8c8T9LcFQSFqWDUb0pQwGXJ8UuCU8sVsLvhQxhsBkbYOobHe1MYrZizLb5eS6+owWeDQntaVuNVgA7J+QkvWny9+mtyGNtRrYFOgpGJMdP44qfqPobPL9C842R6CTg90v15xJq10nr+YCL95DCxhfg==
    GF_AUTH_GITHUB_CLIENT_SECRET: AgB8l1cLFfP164hOXseDha9D7IppWDnPfBlFkkXuVE3kZierB579tbTiDoHtJscF4Z6FqYTfotJjYqC4aCGVktIvuBpt6CcSyMms/ZPAIn/cO4RjVC8mPVGA5E1jIbtioiR8dSdBjVUVcJyE7qz41iOrtXLZruOr+Yer5+58Q8IZ/j+oQNay9B40aSB3/+R6FFpI9yIMPRIwI/xVoTb6UFwI0NmGQG/mhUiPtOJi+XK1CtpuPR3aCzC3vMZAh9HPLVdLVXk+Tvt5fgxxwB0h0WmWgsxB6lWyLzJhtmebwiQgEFlO36j/G/r/YagXqthDPudOFjUSAwuIRu6PV+4aa0/YfV7fxJ3NZ4cmcr8m2UsfnP/z9sEhXgGiwP7P6HGApU6NhZ8E84MJ2JyPF+JFoVQ+/zCQofz2iFIoWUmpXWMCJj/xg0K5XMZZVabjr4NQUMDfQTPSiVoiSUbz/4kGQWBhavOZQUkNlaMGDyxxJhg3SoLugEd+PZnPuHDIolOSGFP5w+Y22vgv6fi8oC5DNXYYxDtBQcNkLF7+oBI35ghqsT5HG3fvXAZzcIGzKFEq4Gn7farT7ZHRWJ6s6c7JV+DJAd99kgag+JiQWhCF0zfWL1HnfqvDqUT7zDIMiu8d7T0Trftuxc0APJyjioSp4dJeSEv04IkdOyJ2H2il6rPm1z3TAXqunx2dn3aG1bn46kgwqVlQB0a4+BS0yY5CjM66/RKxecWWRKB0Fcgi4yijOpFRZTT/NPyy
  template:
    metadata:
      creationTimestamp: null
      name: grafana-oauth
      namespace: monitoring
    type: Opaque
