---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-oauth
  namespace: monitoring
spec:
  encryptedData:
    GF_AUTH_GITHUB_CLIENT_ID: AgCRFGkIvQ5xyn8skNVMyv5ASMwvt9p9uwrFI4j6uwGNAGG0W0BA4eoY1ySsjDVInTc0d5RizMtlI5R5FBonr/Lg1Ba+iYkVmdwfYtQodq/FC2IXVKGgKxkKlxNK3mNM9wECWWfSw2ewz/oAZSSDnuuBWpYuvOYF02DmDvo1TqDKGmv+2E8W4PaqdANuHkImaDyhja0kbw1L8O7k7BtJbNDM8JirfUZg6oHu0ZnyZJ1wvJJgV+czP9514JMjX+fZkn6c0mvrnwHfoPmjRzL9R/PGx5c3wuaL1UmyvAQ/NtIeew86zl5IEE4pxFoFwhdIEoWk2X3jlHCSpqA1/KQOMmNeYa+QcuXkvuE7P7HfO7ol3Ka6LtRNZ7dPnIATHHgxOIekhIBi+D5Snk9I6XwHZY14u8jBVKYwvO6Jw8raYvqlXQlrhgVfXKNBWMYgxHqxBZCpZ4jtMfz52zOcADUSBlr4jwzcijXzxIcIZQtxUm6WXSHUY44eIAuf50XD1cCufKzGtOxIOQ4y3sXgglH4enqEmuRRV3/y/eQJkBTwMXROsBjI5Kyg6XvFWNNVkFcj2VWvW0KI9CY0CgWhcOAZsNsiOi68yzd1WOqEyrO7FDP5Ox9nb3RoTfj/Uw9y02Pq0QJCJpu4pvWPETmYDGcUwNMxFk9EoQsN63cUNg1xM0hZgMumHpuarGhtxxPG+imDONIoV8yvKal+D8wlhI5tSvNtJWzh9g==
    GF_AUTH_GITHUB_CLIENT_SECRET: AgAaSt6bFVG552B8CVZD8SgtMWmsTxVlCDFer+wroWQZ12tuzw0R13Bhk3nBNpdQMlFwuZcFlR9NlWirUnUyBIc1lmQk+mKytvnhRLWZGiW7G+H0yW38q1FjW2VrR/K+GfwW4hXkS/zaMdxXEghBHVIv9Aliwt9ojkWYk9EKyW1vuCY3v6uMP6Lg92ukfpu8v96+izlSVibSPL70zFmIrQTUkc+d8c8s35zkMSAvXyCmzXrTF+AuH5MBAeCczE+uILy0zNVDHgZ5a1Qyn7YRNPRT0XWJd4xN6gxxCl8HrsIk41RywHtzZY1yKFYDzClFNVNJSpz7XLubJTlF/vgBZgS1fJDBXX9TM+p/d0xvxS/v2/h05vGT2ORbPrHDMvtVedv4ThbhaPY4LZiKQm8pHvS89LckuTiyz05D+EKFxhC/N1kWts05qSjVAL6QG+AC27FnNMCbv7/iHNGy3A+MTxzv6wHyyQEzhMmlZZELQwnnL2xhD3Q269pQgMtQDbvJ5ffTF5E4TeX5Gxj0c7w8QlnNN3QgiMtfi3AMRMKc3m1u7vPE6Ame08XO0X0vsxKUuNIQLBQ+cGTk9jMlFLMSfYvIBcycHAEXfdkj4zi1gMNJeTkB9QOaL+g3gx7wiAhGHd5ETAy7z4PKy6GtuzGJBYYbflloWpNKWmZfbXpRskz9L3sM+skFu1zKy46ekxjitrRAgOJcDM5Le9+ZSYslRrZSWUs+4K4IyBR34p3S/0XmFybe7gRTW1nP
  template:
    metadata:
      creationTimestamp: null
      name: grafana-oauth
      namespace: monitoring
