apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring

resources:
  - namespace.yaml
  - prometheus.yaml
  - grafana-oauth-sealed.yaml
  - ingress-route.yaml
  - alertmanager-discord-sealed.yaml

configMapGenerator:
  - name: alertmanager-config
    options:
      disableNameSuffixHash: true
    files:
      - alertmanager.yaml 