apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: loki
  namespace: monitoring
spec:
  repo: https://grafana.github.io/helm-charts
  chart: loki
  version: "5.41.6"
  targetNamespace: monitoring
  valuesContent: |-
    singleBinary:
      replicas: 1
    loki:
      auth_enabled: false
      limits_config:
        volume_enabled: true
      commonConfig:
        replication_factor: 1
      storage:
        type: filesystem
      memberlist:
        join_members: []
      
    nodeSelector:
      node.kubernetes.io/role: ops
    
    tolerations:
      - key: "node.kubernetes.io/role"
        operator: "Equal"
        value: "ops"
        effect: "NoSchedule"
    
    persistence:
      enabled: true
      size: 10Gi
      storageClassName: local-path
      accessModes:
        - ReadWriteOnce
    
    serviceMonitor:
      enabled: true
    
    monitoring:
      selfMonitoring:
        enabled: true
        grafanaAgent:
          installOperator: false
      lokiCanary:
        enabled: true 