apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: loki
  namespace: monitoring
spec:
  repo: https://grafana.github.io/helm-charts
  chart: loki-stack
  version: "2.10.2"
  targetNamespace: monitoring
  valuesContent: |-
    loki:
      image:
        registry: docker.io
        repository: grafana/loki
        tag: 2.9.3
        pullPolicy: IfNotPresent
      auth_enabled: false
      commonConfig:
        replication_factor: 1
      storage:
        type: filesystem
      server:
        http_listen_port: 3100
        grpc_listen_port: 9095
        http_server_read_timeout: 600s
        http_server_write_timeout: 600s
        http_server_idle_timeout: 600s
        log_level: info
      limits_config:
        enforce_metric_name: false
        reject_old_samples: true
        reject_old_samples_max_age: 168h
        max_entries_limit_per_query: 5000
        per_stream_rate_limit: 3MB
        per_stream_rate_limit_burst: 15MB
      query_range:
        align_queries_with_step: true
        max_retries: 5
        split_queries_by_interval: 15m
        cache_results: true
        results_cache:
          cache:
            enable_fifocache: true
            fifocache:
              max_size_bytes: 500MB
      querier:
        max_concurrent: 2048
      frontend:
        max_outstanding_per_tenant: 2048
        compress_responses: true
      frontend_worker:
        match_max_concurrent: true
      ruler:
        enable_api: true
        enable_alertmanager_v2: true
      distributor:
        ring:
          kvstore:
            store: memberlist
    promtail:
      enabled: true
      config:
        logLevel: info
        clients:
          - url: http://loki:3100/loki/api/v1/push
        positions:
          filename: /run/promtail/positions.yaml
        snippets:
          extraScrapeConfigs: |
            - job_name: kubernetes-pods
              kubernetes_sd_configs:
                - role: pod
              pipeline_stages:
                - docker: {}
              relabel_configs:
                - source_labels:
                    - __meta_kubernetes_pod_node_name
                  target_label: node_name
                - source_labels:
                    - __meta_kubernetes_namespace
                  target_label: namespace
                - source_labels:
                    - __meta_kubernetes_pod_name
                  target_label: pod
                - source_labels:
                    - __meta_kubernetes_pod_container_name
                  target_label: container
                - action: replace
                  source_labels:
                    - __meta_kubernetes_pod_uid
                    - __meta_kubernetes_pod_container_name
                  target_label: __path__
                  separator: /
                  replacement: /var/log/pods/*$1/*.log
      defaultVolumes:
        - name: run
          hostPath:
            path: /run/promtail
        - name: containers
          hostPath:
            path: /var/lib/docker/containers
        - name: pods
          hostPath:
            path: /var/log/pods
      defaultVolumeMounts:
        - name: run
          mountPath: /run/promtail
        - name: containers
          mountPath: /var/lib/docker/containers
          readOnly: true
        - name: pods
          mountPath: /var/log/pods
          readOnly: true 