apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: ict-db
  annotations:
    cnpg.io/skipEmptyWalArchiveCheck: "enabled"
spec:
  instances: 1
  postgresql:
    parameters:
      max_connections: "100"
      shared_buffers: "128MB"
  
  resources:
    requests:
      memory: "256Mi"
      cpu: "100m"
    limits:
      memory: "512Mi"
      cpu: "500m"
  
  storage:
    size: 1Gi
    storageClass: local-path

  # Backup configuration
  backup:
    barmanObjectStore:
      destinationPath: "s3://indy-db-backups-development/ict-db"
      endpointURL: "https://s3.amazonaws.com"
      s3Credentials:
        accessKeyId:
          name: aws-creds
          key: ACCESS_KEY_ID
        secretAccessKey:
          name: aws-creds
          key: ACCESS_SECRET_KEY
    retentionPolicy: "30d"

  bootstrap:
    recovery:
      backup:
        name: ict-db-backup
      database: ict 