apiVersion: apps/v1
kind: Deployment
metadata:
  name: vatsim-data-ingestor
spec:
  selector:
    matchLabels:
      app: vatsim-data-ingestor
  template:
    metadata:
      labels:
        app: vatsim-data-ingestor
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
      - name: vatsim-data-ingestor
        image: ghcr.io/indy-center/vatsim-data:latest
        ports:
        - containerPort: 3000
          protocol: TCP
        resources:
          requests:
            cpu: 100m 
            memory: 256Mi
          limits:
            cpu: 200m
            memory: 512Mi
        env:
          - name: ZMQ_PORT
            value: "3000"
          - name: ZMQ_HOST
            value: "*"
          - name: VATSIM_DATA_URL
            value: https://data.vatsim.net/v3/vatsim-data.json
          - name: REFRESH_INTERVAL_MS
            value: "15000"
          - name: LOG_LEVEL
            value: debug
