apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ict-production
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: ict=ghcr.io/indy-center/controller-tools:1-main
    argocd-image-updater.argoproj.io/ict.pull-secret: pullsecret:argocd/ghcr-secret
    argocd-image-updater.argoproj.io/ict.update-strategy: name
    argocd-image-updater.argoproj.io/ict.allow-tags: regexp:^[0-9]+-main$
    argocd-image-updater.argoproj.io/ict.force-update: "true"
spec:
  project: apps
  source:
    repoURL: https://github.com/indy-center/infrastructure.git
    targetRevision: HEAD
    path: apps/ict/overlays/production
  destination:
    server: https://kubernetes.default.svc
    namespace: production
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true 